/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ILayerZeroAdapter,
  ILayerZeroAdapterInterface,
} from "./ILayerZeroAdapter";

const _abi = [
  {
    inputs: [],
    name: "VERSION",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ILayerZeroAdapter__factory {
  static readonly abi = _abi;
  static createInterface(): ILayerZeroAdapterInterface {
    return new utils.Interface(_abi) as ILayerZeroAdapterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILayerZeroAdapter {
    return new Contract(address, _abi, signerOrProvider) as ILayerZeroAdapter;
  }
}
