/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace IMetaDelegateHelper {
  export type MetaDelegateParamsStruct = {
    underlyingAsset: PromiseOrValue<string>;
    delegationType: PromiseOrValue<BigNumberish>;
    delegator: PromiseOrValue<string>;
    delegatee: PromiseOrValue<string>;
    deadline: PromiseOrValue<BigNumberish>;
    v: PromiseOrValue<BigNumberish>;
    r: PromiseOrValue<BytesLike>;
    s: PromiseOrValue<BytesLike>;
  };

  export type MetaDelegateParamsStructOutput = [
    string,
    number,
    string,
    string,
    BigNumber,
    number,
    string,
    string
  ] & {
    underlyingAsset: string;
    delegationType: number;
    delegator: string;
    delegatee: string;
    deadline: BigNumber;
    v: number;
    r: string;
    s: string;
  };
}

export interface IMetaDelegateHelperInterface extends utils.Interface {
  functions: {
    "batchMetaDelegate((address,uint8,address,address,uint256,uint8,bytes32,bytes32)[])": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "batchMetaDelegate"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "batchMetaDelegate",
    values: [IMetaDelegateHelper.MetaDelegateParamsStruct[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchMetaDelegate",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IMetaDelegateHelper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IMetaDelegateHelperInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    batchMetaDelegate(
      delegateParams: IMetaDelegateHelper.MetaDelegateParamsStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  batchMetaDelegate(
    delegateParams: IMetaDelegateHelper.MetaDelegateParamsStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    batchMetaDelegate(
      delegateParams: IMetaDelegateHelper.MetaDelegateParamsStruct[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    batchMetaDelegate(
      delegateParams: IMetaDelegateHelper.MetaDelegateParamsStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    batchMetaDelegate(
      delegateParams: IMetaDelegateHelper.MetaDelegateParamsStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
